// <auto-generated />
namespace Hunters_Books.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration25));
        
        string IMigrationMetadata.Id
        {
            get { return "202304201056097_migration2.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
